name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: [self-hosted, Linux, X64]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      working-directory: ./RBCAcademy
      run: dotnet restore
    - name: Test
      working-directory: ./RBCAcademy
      run: dotnet test --verbosity normal
    - name: Build
      working-directory: ./RBCAcademy
      run: dotnet publish --no-restore


